import = [
  "~/.config/alacritty/themes/themes/dario.toml"
]
shell = "zsh"
[font]
normal = { family = "Spleen 6x12", style = "Medium"}
size = 9
[window]
  opacity =  0.95 #default
  decorations = "Full"
  padding = { x = 15, y = 20 } #for Martian

[colors]
cursor = {  cursor = "#ebdbb2" }

[scrolling]
multiplier = 1
